/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI
 * OpenAPI spec version: 1.0.0
 */
import type { Mechanic } from './mechanic';
import type { User } from './user';
import type { Plate } from './plate';

export interface Car {
  id: number;
  /** @nullable */
  model: string | null;
  /** @nullable */
  mechanic?: Mechanic;
  /** @nullable */
  owner?: User;
  /** @nullable */
  plate?: Plate;
}
