/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI
 * OpenAPI spec version: 1.0.0
 */

export type CarLengthAwarePaginatorLinksItem = {
  url?: string;
  label?: string;
  active?: boolean;
};
