/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI
 * OpenAPI spec version: 1.0.0
 */
import type { CarLengthAwarePaginatorLinksItem } from './carLengthAwarePaginatorLinksItem';
import type { Car } from './car';

export interface CarLengthAwarePaginator {
  current_page?: number;
  first_page_url?: string;
  from?: number;
  last_page?: number;
  last_page_url?: string;
  links?: CarLengthAwarePaginatorLinksItem[];
  next_page_url?: string;
  path?: string;
  per_page?: number;
  prev_page_url?: string;
  to?: number;
  total?: number;
  data?: Car[];
}
