/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';
import type { Car } from './car';
import type { Plate } from './plate';
import type { Mechanic } from './mechanic';

export type GarageUser200 = {
  user?: User;
  car?: Car;
  plate?: Plate;
  mechanic?: Mechanic;
  requestedTime?: string;
};
