/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI
 * OpenAPI spec version: 1.0.0
 */
import type { Car } from './car';
import type { User } from './user';

export interface Mechanic {
  id: number;
  /** @nullable */
  name: string | null;
  /** @nullable */
  cars?: Car[] | null;
  /** @nullable */
  clients?: User[] | null;
}
