/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI
 * OpenAPI spec version: 1.0.0
 */
import type { Car } from './car';

export interface Plate {
  id: number;
  number: string;
  /** @nullable */
  car?: Car;
}
