/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI
 * OpenAPI spec version: 1.0.0
 */
import type { Car } from './car';
import type { Plate } from './plate';

export interface User {
  id: number;
  name: string;
  email: string;
  /** @nullable */
  car?: Car;
  /** @nullable */
  carPlate?: Plate;
}
